echo "Wait, if 'inputs.mode' evaluation was correct all along (because we proved it worked for prepare-release-tag), what else?"
echo "Maybe 'run_release=true' failed to assign correctly?"
echo "Wait, could it be that 'is_nightly=true' overwrote 'run_release=true'?"
echo "No, they are separate variables."
echo "Could it be that 'run_release' is exported but lost?"
echo "No, 'echo \"run_release=\$run_release\" >> \"\$GITHUB_OUTPUT\"' handles it."
echo "If inputs.mode evaluated to 'release-*' literally?"
echo "No, github actions expands inputs.mode."
echo "Wait! The issue is 'I am expecting github releases with downloads when I run a tag release'"
echo "If they ran a tag release FROM THE UI using the Tags view -> 'Create new release' -> Publish release."
echo "That creates a 'release' event."
echo "For a 'release' event, the Route job sets run_release=true."
echo "Then 'build-release-deb' runs and produces the artifact."
echo "Then 'publish-release' runs and tries to create the release:"
echo "gh release create \"\$TAG\" new-deb/*.deb"
echo "But the release ALREADY EXISTS."
echo "So 'gh release create' fails."
echo "Then 'gh release create ... || true' catches the error, but the deb file is NEVER UPLOADED!"
echo "This is EXACTLY why 'github releases with downloads' was missing the downloads!"
echo "To fix it, we just need to ADD the 'gh release upload' fallback!"
