echo "Wait... Is that the only thing?"
echo "Let's review 'publish-release' job logic."
echo "      - name: Tag commit for release (workflow_dispatch)"
echo "        if: \${{ github.event_name == 'workflow_dispatch' && startsWith(inputs.mode, 'release-') }}"
echo "        run: |"
echo "          git tag -f \${{ needs.prepare-release-tag.outputs.release_tag }}"
echo "          git push -f origin \${{ needs.prepare-release-tag.outputs.release_tag }}"
echo "Wait, if github.event_name is 'push', it won't tag again."
echo "BUT if 'github.event_name' is 'release'?"
echo "If 'release', it also won't tag. And TAG will be github.ref_name."
echo "So it's fine."
echo "Wait, what about the 'gh release create' command?"
echo "          # Use Announcement category if possible, else standard notes"
echo "          gh release create \"\$TAG\" new-deb/*.deb --generate-notes \$prerelease --discussion-category Announcements || \\"
echo "            gh release create \"\$TAG\" new-deb/*.deb --generate-notes \$prerelease || true"
echo "What if 'new-deb/*.deb' has NO matches? It won't have NO matches because 'build-release-deb' uploads an artifact, and we downloaded it."
echo "But if we are triggering via 'release' (UI), the release is ALREADY created!"
echo "If the release is already created, 'gh release create' will FAIL!"
echo "If it fails, it hits '|| true'. BUT it won't upload the deb to the existing release!"
echo "To upload an asset to an EXISTING release, we should use 'gh release upload \"\$TAG\" new-deb/*.deb'!"
echo "Wait, does the user want the workflow to CREATE the release?"
echo "If they triggered via 'workflow_dispatch' or 'push' (tag), the release does NOT exist, so 'gh release create' works and uploads the asset."
echo "Wait, the blog post says:"
echo "gh release create \"\$TAG\" new-deb/*.deb --generate-notes \$prerelease --discussion-category Announcements || \\"
echo "  gh release create \"\$TAG\" new-deb/*.deb --generate-notes \$prerelease || true"
echo "This is what is currently in ci.yml."
echo "Is it possible that github actions throws an error on 'gh release create' if the tag already has a release? Yes. And '|| true' ignores it."
echo "But if it ignores it, the asset is NOT uploaded!"
