echo "Wait. If run_release is false, build-release-deb skips."
echo "If build-release-deb skips, it doesn't show in API? Sometimes skipped jobs that skip due to 'if' are completely dropped from the list in some github API contexts? Wait, no, usually they show up."
echo "Could it be that the run_release check is: \${{ needs.route.outputs.run_release == 'true' }}"
echo "Let me check if run_release is evaluated to false!"
echo "If it evaluates to false, why would [[ \"\${{ inputs.mode }}\" == release-* ]] be false?"
echo "Maybe github actions 'inputs.mode' in bash evaluates to empty when triggered by certain things?"
echo "If 'inputs.mode' is empty, then startsWith(inputs.mode, 'release-') is FALSE."
echo "BUT startsWith(inputs.mode, 'release-') was TRUE (because prepare-release-tag ran)!"
echo "So inputs.mode WAS 'release-something'."
echo "Why would bash [[ \"release-something\" == release-* ]] be false?"
echo "Maybe 'release-*' should not be quoted? It is NOT quoted."
echo "Is it possible that run_release=true is overwritten?"
