echo "Wait, if the user triggered it via workflow dispatch (run 29394511279 was workflow_dispatch)."
echo "And prepare-release-tag RAN."
echo "If prepare-release-tag ran, it means github.event_name == 'workflow_dispatch' AND startsWith(inputs.mode, 'release-') was TRUE!"
echo "So inputs.mode WAS a release-* value!"
echo "If inputs.mode was a release-* value, why did run_release evaluate to false in Route event?"
echo "Because in Route event, the code is:"
echo "            workflow_dispatch)"
echo "              run_code_checks=true"
echo "              if [[ \"\${{ inputs.mode }}\" == release-* ]]; then"
echo "                run_release=true"
echo "              fi"
echo "Is there something wrong with how inputs.mode is evaluated in the script?"
echo "Or wait! Is 'release-*' not expanding?"
echo "No, in bash [[ \"release-test\" == release-* ]] is true."
echo "Wait. What if I check the exact text of Route event in the file?"
