echo "Wait, when you look at run 29394511279, which the user linked..."
echo "The user linked run 29394511279."
echo "If I look at run 29394511279, the jobs that ran were:"
echo "Route event, Prepare release tag, Classic C Makefile build."
echo "build-release-deb DID NOT RUN!"
echo "If build-release-deb did not run, publish-release did not run."
echo "Why did build-release-deb not run in 29394511279?"
echo "Because run_release was FALSE."
echo "Why was run_release FALSE in 29394511279?"
echo "Because in Route event, the code is:"
echo "              if [[ \"\${{ inputs.mode }}\" == release-* ]]; then"
echo "                run_release=true"
echo "              fi"
echo "Wait. We established earlier that startsWith(inputs.mode, 'release-') MUST be true because prepare-release-tag RAN."
echo "Wait! prepare-release-tag condition is:"
echo "if: \${{ github.event_name == 'workflow_dispatch' && startsWith(inputs.mode, 'release-') }}"
echo "Is it possible that github actions evaluates startsWith('lint-fix', 'release-') to FALSE, and so it SKIPS prepare-release-tag?"
echo "Let me check the status of 'Prepare release tag' in run 29394511279."
echo "Wait, in my earlier API output:"
echo "{ 'name': 'Prepare release tag', 'status': 'completed', 'conclusion': 'success' }"
echo "It says SUCCESS! Not skipped!"
echo "So prepare-release-tag DID RUN and succeeded!"
echo "So inputs.mode WAS 'release-*'!"
echo "So WHY was run_release FALSE in Route event?!?!?!"
