echo "Is it possible that github.event_name is 'push' but github.ref is NOT 'refs/tags/v1.0.0'?"
echo "If it is a push to master, run_release evaluates to FALSE."
echo "If the user creates a tag through the GitHub UI (e.g. 'Create a new release' -> 'Choose a tag' -> 'Create new tag'), what is the github.event_name?"
echo "It triggers a 'push' event for the new tag!"
echo "And it ALSO triggers a 'release' event (type: published)!"
echo "Let's check Route event for 'release':"
echo "            release)"
echo "              run_release=true"
echo "              ;;"
echo "If run_release=true for 'release' event, build-release-deb runs."
echo "publish-release runs."
echo "BUT wait! If it is a 'release' event, what is 'TAG' in publish-release?"
echo "          TAG: \${{ github.event_name == 'workflow_dispatch' && needs.prepare-release-tag.outputs.release_tag || github.ref_name }}"
echo "For 'release' event, github.ref_name is the tag name."
echo "So it works!"
echo "What if the bug is that in publish-release, needs.prepare-release-tag MUST be successful?"
echo "No, !failure() allows it to run."
echo "Wait, if 'publish-release' depends on 'prepare-release-tag' and 'prepare-release-tag' is SKIPPED, github actions WILL skip 'publish-release' UNLESS you use 'always()' or 'success()' etc?"
echo "Wait, github actions evaluates '!failure() && !cancelled()' as 'always() && !failure() && !cancelled()'."
echo "Wait. Does '!failure()' override the skip behavior?"
echo "Let's check GitHub Actions documentation: 'If you use any expression that does not contain a status check function, it will automatically be prefixed with success() &&.'"
echo "But '!failure()' DOES NOT contain success()!"
echo "Ah! The only status check functions are 'success()', 'always()', 'cancelled()', 'failure()'."
echo "Is '!failure()' valid?"
echo "Yes, '!failure()' contains 'failure()'."
echo "So 'success()' is NOT prefixed."
echo "So it runs!"
