echo "Wait..."
echo "Is it possible that build-release-deb DID run but I didn't see it because it is not named 'build-release-deb' in the jobs API?"
echo "Look at the API output:"
echo "Route event"
echo "Prepare release tag"
echo "Classic C Makefile build"
echo "It only has 3 jobs!"
echo "If build-release-deb was skipped, it usually shows up as skipped."
echo "If it is not in the API output, it means the workflow parsed but the job was completely dropped. Wait, why would it be dropped?"
echo "If it has 'if: false'?"
echo "No, 'if: \${{ needs.route.outputs.run_release == 'true' }}'."
echo "Wait! Is it possible that 'run_release' evaluated to false, so it skipped, and then 'publish-release' ALSO skipped because it depends on it, and GitHub Actions drops jobs that are skipped due to a false 'if' condition from some API responses? Yes!"
echo "But if it skipped, then NO release was made."
echo "Why was run_release false?"
echo "Let me change the condition in Route event to:"
echo "              if [[ \"\${{ inputs.mode }}\" == release-* ]]; then"
echo "to"
echo "              if [[ \"\${{ inputs.mode }}\" == release-* ]]; then"
echo "Wait, is [[ \"release-minor\" == release-* ]] valid?"
echo "Yes."
echo "Wait, what if inputs.mode in Route event uses double quotes, and github actions evaluates it inside the double quotes."
echo "If the user provided inputs.mode=release-minor, it evaluates to:"
echo "if [[ \"release-minor\" == release-* ]]; then"
echo "Which is TRUE!"
echo "Why would it evaluate to FALSE?"
