echo "Ah! 'build-release-deb' uses 'armv7' in 'uraimo/run-on-arch-action@v2' which is completely fine."
echo "But if 'run_release' is 'false', it skips it. When skipped, it usually shows up as skipped."
echo "Wait, is it possible that 'run_release' is indeed true, but the 'if' condition is evaluated as false?"
echo "Let's check the 'if' condition."
echo "if: \${{ needs.route.outputs.run_release == 'true' }}"
echo "This evaluates correctly."
echo "Is it possible that github actions drops skipped jobs from the API response entirely? Maybe."
echo "Wait! Is there an issue with the PR?"
echo "There's a PR recently merged 'fix-deb-build-ci'"
echo "Let's see what that PR changed!"
