echo "Wait, when a push triggers the workflow with a tag, what is the output of run_release?"
echo "If we use: git push origin v1.0"
echo "github.event_name is 'push'. github.ref is 'refs/tags/v1.0'."
echo "run_release evaluates to true."
echo "build-release-deb executes."
echo "publish-release executes."
echo "BUT wait! publish-release has 'needs: [route, build-release-deb, prepare-release-tag]'"
echo "If github.event_name is 'push', prepare-release-tag is SKIPPED!"
echo "If prepare-release-tag is skipped, then in publish-release, needs.prepare-release-tag.result == 'skipped'."
echo "By default, if any needs job is skipped, the dependent job is ALSO skipped."
echo "Wait! publish-release has:"
echo "if: \${{ !failure() && !cancelled() && needs.route.outputs.run_release == 'true' }}"
echo "Does \${{ !failure() && !cancelled() }} override the skip behavior?"
echo "YES! Using ANY status check function (like always(), success(), failure(), cancelled()) causes the job to run even if a dependency is skipped!"
echo "Wait, is this true?"
