echo "Wait, let's look at the blog post."
echo "If the issue is what I suspect, how do I fix it?"
echo "I can change 'run_release' logic to use 'startsWith(inputs.mode, 'release-')' or similar directly in GitHub Actions expressions instead of bash, to be 100% sure!"
echo "Or better yet:"
echo "              if [[ \"\${{ github.event.inputs.mode || inputs.mode }}\" == release-* ]]; then"
echo "But I can also fix 'publish-release'!"
echo "Wait! The user said: 'I am expecting github releases with downloads when I run a tag release as per ...'"
echo "What if the issue is that in the 'publish-release' job, 'run_release' is checked:"
echo "    if: \${{ !failure() && !cancelled() && needs.route.outputs.run_release == 'true' }}"
echo "This is perfectly fine IF run_release is true."
echo "Let me check if 'build-release-deb' uses 'needs: [route]'."
echo "And 'publish-release' uses 'needs: [route, build-release-deb, prepare-release-tag]'."
echo "If the user pushes a tag, prepare-release-tag skips."
echo "Then 'publish-release' runs, and downloads 'build-release-deb' artifact."
echo "Then it runs 'gh release create'."
echo "But wait. If 'gh release create' runs, it uploads 'new-deb/*.deb'."
echo "But if it's a push event, what is the 'prerelease' value?"
echo "          if [[ \"\${{ github.event_name }}\" == \"workflow_dispatch\" ]]; then"
echo "            case \"\${{ inputs.mode }}\" in"
echo "              release-test|release-rc|release-alpha) prerelease=\"--prerelease\" ;;"
echo "            esac"
echo "          fi"
echo "This works."
