echo "Maybe github actions 'inputs' context is empty in the 'run' scope, and you MUST use 'github.event.inputs.mode'?"
echo "Let's check if 'inputs' is available in 'run'."
echo "According to GitHub Actions documentation for 'inputs' context:"
echo "'The inputs context is only available for reusable workflows. For workflow_dispatch, you must use github.event.inputs'"
echo "WAIT!!"
echo "IS IT ONLY FOR REUSABLE WORKFLOWS?!"
echo "Let's verify this!"
echo "If inputs context is only for reusable workflows, then \${{ inputs.mode }} is empty in a workflow_dispatch event in the 'run' block!"
echo "But in 'if' conditions, github actions MIGHT fallback or it might evaluate to false?"
echo "Wait, 'startsWith(inputs.mode, 'release-')' evaluated to TRUE!"
echo "Why would it evaluate to true in 'if' but empty in 'run'?"
echo "Actually, 'inputs' IS available for workflow_dispatch."
