echo "Wait, let's look at the blog post again:"
echo "              if [[ \"\${{ inputs.mode }}\" == release-* ]]; then"
echo "Is it possible that github actions replaces \${{ inputs.mode }} correctly, but the bash syntax is wrong?"
echo "Let's test this in bash!"
echo "mode=\"release-patch\""
echo "if [[ \"\$mode\" == release-* ]]; then echo yes; fi"
echo "Wait, what if inputs.mode is replaced, it becomes:"
echo "if [[ \"release-patch\" == release-* ]]; then"
echo "This works."
echo "What if run_release is correctly evaluated to true?"
echo "Then route outputs run_release=true."
echo "Then build-release-deb checks \${{ needs.route.outputs.run_release == 'true' }}."
echo "This matches."
echo "Then build-release-deb should RUN."
echo "BUT it didn't run. WHY didn't it run?"
