echo "Wait, if inputs.mode was 'release-*', why did run_release evaluate to false in Route event?"
echo "Because in Route event:"
echo "if [[ \"\${{ inputs.mode }}\" == release-* ]]; then"
echo "  run_release=true"
echo "fi"
echo "What if github.event.inputs.mode is used instead of inputs.mode?"
echo "Both should work in bash."
echo "Could it be a syntax error in the bash script that causes the step to fail? No, Route event completed successfully."
echo "Could it be that github.event_name is 'push' but they manually triggered it?"
echo "No, event is 'workflow_dispatch'."
echo "What if there is a typo in Route event?"
