echo "Wait, let's look at the full workflow dispatch block:"
echo "            workflow_dispatch)"
echo "              run_code_checks=true"
echo "              if [[ \"\${{ inputs.mode }}\" == release-* ]]; then"
echo "                run_release=true"
echo "              fi"
echo "Ah, in bash, if we write:"
echo "if [[ \"\${{ inputs.mode }}\" == release-* ]]; then"
echo "Actually, \${{ inputs.mode }} is evaluated BEFORE bash executes."
echo "Wait, what if inputs.mode is literally 'release-*'?"
echo "No, it is a choice input. 'release-major', 'release-minor', etc."
echo "What if the bug is something else?"
echo "Let's check the rest of the 'publish-release' job dependencies."
