echo "Wait, when prepare-release-tag is skipped, it returns a skipped result."
echo "Wait, I found out! In run 29394511279, prepare-release-tag RAN."
echo "If prepare-release-tag RAN, run_release MUST HAVE BEEN true!"
echo "If run_release was true, why did build-release-deb NOT run?"
echo "Maybe build-release-deb FAILED?"
echo "If it failed, it would show as failed."
echo "Wait, the API output only showed 3 jobs: Route event, Prepare release tag, Classic C Makefile build."
echo "Why did the other jobs not show up at all?"
echo "Maybe github action syntax error in build-release-deb? No, the action parsed."
