echo "Wait, when we push a tag, github.event_name is 'push'. github.ref is 'refs/tags/v1.0'."
echo "run_release is evaluated to TRUE."
echo "So needs.route.outputs.run_release == 'true'."
echo "So 'build-release-deb' SHOULD RUN for a tag push."
echo "BUT the user said: 'I am expecting github releases with downloads when I run a tag release as per arran4.github.io...'"
echo "Wait! The user linked run 29394511279, which is a 'workflow_dispatch' event."
echo "Why did the user link a 'workflow_dispatch' event if they ran a 'tag release'?"
echo "Because they used the 'Run workflow' button and selected 'release-...' mode!"
echo "If they did that, then 'prepare-release-tag' ran successfully (we saw this in the API)."
echo "If 'prepare-release-tag' ran successfully, it created a new tag (e.g. v2.0.0) and PUSHED it!"
echo "Look at 'prepare-release-tag':"
echo "It only outputs the tag."
echo "Then 'publish-release' pushes the tag."
echo "Let's check publish-release:"
echo "      - name: Tag commit for release (workflow_dispatch)"
echo "        if: \${{ github.event_name == 'workflow_dispatch' && startsWith(inputs.mode, 'release-') }}"
echo "        run: |"
echo "          git tag -f \${{ needs.prepare-release-tag.outputs.release_tag }}"
echo "          git push -f origin \${{ needs.prepare-release-tag.outputs.release_tag }}"
echo "Wait, if 'publish-release' didn't run, the tag wasn't pushed!"
echo "Why didn't 'publish-release' run in 29394511279?"
echo "Because 'build-release-deb' was SKIPPED?"
echo "Wait! 'publish-release' has 'needs: [route, build-release-deb, prepare-release-tag]'!"
echo "If 'build-release-deb' is SKIPPED, then 'publish-release' is ALSO skipped unless it has '!failure() && !cancelled()'..."
echo "Wait! It DOES have '!failure() && !cancelled()'!"
