echo "Wait, when a matrix is used and the matrix is empty, it drops the job."
echo "But build-release-deb doesn't use a matrix."
echo "What if run_release evaluates to 'true' in Route, but in outputs it maps to nothing?"
echo "Route event outputs:"
echo "      run_release: \${{ steps.route.outputs.run_release }}"
echo "Is it correctly mapped? Yes, id: route."
echo "What if in github actions, a step like 'uraimo/run-on-arch-action@v2' is not available or has an issue? No, it would fail."
echo "Wait, if run_release was true, build-release-deb would run."
echo "Since it didn't run and didn't even show as skipped, maybe run_release was FALSE!"
echo "If run_release was FALSE, why did prepare-release-tag RUN?"
echo "prepare-release-tag condition is:"
echo "if: \${{ github.event_name == 'workflow_dispatch' && startsWith(inputs.mode, 'release-') }}"
echo "It does NOT depend on run_release!!!"
echo "Ah! prepare-release-tag only depends on inputs.mode."
echo "So prepare-release-tag runs because inputs.mode == 'release-patch'."
echo "But run_release is FALSE, so build-release-deb skips."
echo "Why is run_release FALSE when inputs.mode == 'release-patch'?"
echo "Because in Route event:"
echo "              if [[ \"\${{ inputs.mode }}\" == release-* ]]; then"
echo "                run_release=true"
echo "              fi"
echo "Wait, does github actions 'startsWith' evaluate correctly for 'release-patch'?"
echo "Yes, startsWith('release-patch', 'release-') is true."
echo "Does bash [[ \"release-patch\" == release-* ]] evaluate to true?"
echo "Yes, it does."
echo "BUT WAIT!!! What if \${{ inputs.mode }} is NOT passed correctly to the bash script?"
echo "Look at:"
echo "              if [[ \"\${{ github.event.inputs.mode || inputs.mode }}\" == release-* ]]; then"
