echo "In the blog, there is no single publish-release, there is publish-draft and promote-release."
echo "Wait, let's look at build-release-deb:"
echo "    name: Build Debian Release Package"
echo "    needs: [route]"
echo "    if: \${{ needs.route.outputs.run_release == 'true' }}"
echo "Is it possible that github actions requires string comparisons to be double quotes?"
echo "No, single quotes are fine."
echo "What if outputs in Route event is not passing correctly?"
echo "Let's check Route event steps:"
echo "          echo \"run_release=\$run_release\" >> \"\$GITHUB_OUTPUT\""
echo "This seems correct."
