echo "Wait! The user linked run 29394511279, which was a 'workflow_dispatch' event."
echo "If the issue was that 'publish-release' didn't upload, why did 'build-release-deb' NOT run in 29394511279?"
echo "Maybe 'build-release-deb' DID run, but I couldn't see it in the API?"
echo "Let's check if there are ANY artifacts from run 29394511279."
echo "I checked earlier and there were 0 artifacts."
echo "If there were 0 artifacts, 'build-release-deb' didn't run."
echo "Why did 'build-release-deb' not run?"
echo "Because 'run_release' evaluated to false!"
echo "Why did it evaluate to false?"
echo "Because the evaluation in bash was:"
echo "if [[ \"\${{ inputs.mode }}\" == release-* ]]; then"
echo "What if the user provided inputs.mode=release-patch, but they provided it via API or via older workflow where \${{ github.event.inputs.mode }} is needed?"
echo "I will apply the fix to inputs.mode evaluation AND the gh release upload."
