echo "Wait... the issue states: 'I am expecting github releases with downloads when I run a tag release as per arran4.github.io/blog/post/2026/011-simplified-github-ci/'"
echo "What did the author say? In the article:"
echo "'If you publish Homebrew formulas...'"
echo "'Important scope rule: only add binary build/release lanes when the project actually produces binaries.'"
echo "Wait! The user mentions: 'I am expecting github releases with downloads when I run a tag release...'"
echo "If we look at 'publish-release' job in ci.yml:"
echo "      - name: Publish GitHub Release"
echo "        env:"
echo "          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}"
echo "          TAG: \${{ github.event_name == 'workflow_dispatch' && needs.prepare-release-tag.outputs.release_tag || github.ref_name }}"
echo "        run: |"
echo "          set -euo pipefail"
echo "          ..."
echo "          gh release create \"\$TAG\" new-deb/*.deb --generate-notes \$prerelease --discussion-category Announcements || \\"
echo "            gh release create \"\$TAG\" new-deb/*.deb --generate-notes \$prerelease || true"
echo "Is it possible that 'new-deb/*.deb' fails to match and returns an error? But it uses '|| true'!"
echo "If it uses '|| true', it wouldn't fail the build."
echo "But if 'gh release create' fails, there is NO release!"
echo "Wait, if 'new-deb/*.deb' doesn't exist, gh release create might fail."
echo "Wait! The user's action run is 29394511279."
echo "In 29394511279, build-release-deb DID NOT RUN!"
echo "Why did build-release-deb not run?"
echo "Because 'run_release' evaluated to false?"
echo "Let's check Route event script for run_release again."
