echo "Is inputs available inside bash via \${{ inputs.mode }}?"
echo "Yes, it evaluates before."
echo "Could it be that in \${{ inputs.mode }} github evaluates it to an empty string because inputs context is not passed properly?"
echo "Yes, if the workflow dispatch was run without explicitly specifying inputs, \${{ inputs.mode }} is empty unless 'default' is applied. 'default' is applied by GitHub Actions."
echo "If \${{ inputs.mode }} evaluates to 'lint-fix' (the default), then 'if [[ \"lint-fix\" == release-* ]]' is FALSE."
echo "If the user wanted to trigger a release via workflow dispatch, they needed to select 'release-...' in the mode."
echo "If they did select 'release-...', then it evaluates to TRUE."
echo "If run_release is evaluated to TRUE, then build-release-deb WILL run!"
echo "If the user says 'when I run a tag release as per arran4.github.io...', they mean they push a tag?"
echo "If they push a tag, github.event_name is 'push'. github.ref is 'refs/tags/vXXX'."
echo "run_release evaluates to true."
echo "So build-release-deb WILL run."
echo "Then 'publish-release' WILL run."
echo "BUT wait!"
echo "Let's check 'publish-release' dependencies!"
echo "    needs: [route, build-release-deb, prepare-release-tag]"
echo "If they PUSH a tag, prepare-release-tag is SKIPPED."
echo "When prepare-release-tag is skipped, 'publish-release' is ALSO SKIPPED unless it has '!failure() && !cancelled()'."
echo "Wait, if prepare-release-tag is skipped, its status is 'skipped'."
echo "'!failure()' is TRUE because 'skipped' is not 'failure'."
echo "'!cancelled()' is TRUE."
echo "'needs.route.outputs.run_release == 'true'' is TRUE."
echo "So 'publish-release' WILL run!"
echo "BUT wait! If prepare-release-tag is SKIPPED, then 'publish-release' runs, BUT does it have a tag?"
echo "          TAG: \${{ github.event_name == 'workflow_dispatch' && needs.prepare-release-tag.outputs.release_tag || github.ref_name }}"
echo "Yes, TAG will be github.ref_name, which is 'v1.0.0'."
echo "So 'publish-release' SHOULD work!"
