echo "Zero artifacts! So build-release-deb DID NOT RUN!"
echo "If build-release-deb did not run, why?"
echo "Because needs.route.outputs.run_release != 'true'."
echo "Why is it not true?"
echo "Look at Route event script!"
echo "              if [[ \"\${{ inputs.mode }}\" == release-* ]]; then"
echo "What if inputs.mode was NOT 'release-*'?"
echo "If inputs.mode was NOT 'release-*', how did prepare-release-tag run?!"
echo "prepare-release-tag condition:"
echo "if: \${{ github.event_name == 'workflow_dispatch' && startsWith(inputs.mode, 'release-') }}"
echo "Ah! Is 'inputs' referring to github.event.inputs or inputs?"
echo "In 'if:', 'inputs' means 'inputs' context. "
echo "In 'run:', \${{ inputs.mode }} means 'inputs' context."
echo "If startsWith(inputs.mode, 'release-') is TRUE, then \${{ inputs.mode }} MUST be 'release-something'."
echo "BUT what if the script fails?"
echo "We already know Route event succeeded."
echo "Could it be that 'run_release=true' is not correctly written to outputs?"
echo "Look at the end of Route event:"
echo "          echo \"run_release=\$run_release\" >> \"\$GITHUB_OUTPUT\""
echo "If run_release=true, it writes run_release=true."
echo "BUT WAIT!"
echo "              if [[ \"\${{ inputs.mode }}\" == \"lint-fix\" ]]; then"
echo "                is_nightly=true"
echo "              fi"
echo "Is it possible that inputs.mode is BOTH 'release-*' and something else? No."
echo "Wait, let's look at the bash output of Route Event from my API request..."
