echo "Yes, it matches!"
echo "So if it matches, run_release evaluates to true."
echo "If run_release is true, build-release-deb runs."
echo "Wait! The bug must be in prepare-release-tag!"
echo "If a user PUSHES a tag, 'prepare-release-tag' is SKIPPED because its if condition is:"
echo "if: \${{ github.event_name == 'workflow_dispatch' && startsWith(inputs.mode, 'release-') }}"
echo "Then 'publish-release' depends on 'prepare-release-tag'."
echo "if: \${{ !failure() && !cancelled() && needs.route.outputs.run_release == 'true' }}"
echo "Because 'prepare-release-tag' is skipped, its status is 'skipped'."
echo "So 'publish-release' will RUN!"
echo "But in 'publish-release', it uses 'needs.prepare-release-tag.outputs.release_tag' which is NULL!"
echo "Wait, 'TAG' is evaluated as:"
echo "TAG: \${{ github.event_name == 'workflow_dispatch' && needs.prepare-release-tag.outputs.release_tag || github.ref_name }}"
echo "This works! If it's a push event, it uses github.ref_name!"
echo "So 'TAG' is correct."
echo "Then why does it say: 'I am expecting github releases with downloads when I run a tag release'?"
echo "Maybe the issue is with WORKFLOW_DISPATCH run_release!"
echo "In Route event, workflow_dispatch sets run_release=true if inputs.mode == release-*"
echo "Is inputs.mode accessible via github.event.inputs.mode or inputs.mode?"
echo "Yes, github actions replaces \${{ inputs.mode }} with the string value."
