echo "Wait, let's look at the blog post's code again:"
echo "              if [[ \"\${{ inputs.mode }}\" == release-* ]]; then"
echo "Is it possible that github actions has a bug with 'release-*' unquoted in bash, inside '[[ ... ]]'?"
echo "No, '[[ ... ]]' is the bash test command and RHS is treated as a glob pattern if not quoted."
echo "Could it be that the shell used is NOT bash?"
echo "Let's check Route event:"
echo "      - id: route"
echo "        shell: bash"
echo "Yes, it is bash."
