echo "Wait, if the user explicitly says: 'when I run a tag release as per ...'"
echo "What did they actually do?"
echo "They created a 'tag' release (maybe via UI?)"
echo "If they created a tag release via UI, the event is 'release'."
echo "If event is 'release', github.ref_name is the tag (e.g. v1.0.0)."
echo "Then it does 'gh release create \"\$TAG\" new-deb/*.deb' which fails because the release already exists!"
echo "Then it hits '|| true'."
echo "And then NO deb is uploaded!"
echo "This perfectly explains why they are missing the download (the deb file)!"
echo "If this is the case, we should ADD an upload command if 'gh release create' fails, OR just use 'gh release upload'."
echo "Actually, we can try to upload first, or try to create first and then upload if it exists."
echo "gh release upload \"\$TAG\" new-deb/*.deb --clobber"
echo "Let's change the step to:"
echo "          gh release create \"\$TAG\" new-deb/*.deb --generate-notes \$prerelease --discussion-category Announcements || \\"
echo "            gh release create \"\$TAG\" new-deb/*.deb --generate-notes \$prerelease || \\"
echo "            gh release upload \"\$TAG\" new-deb/*.deb --clobber || true"
