echo "Wait, let's check GitHub Actions documentation for github.event.inputs vs inputs."
echo "inputs is only available in workflow_dispatch."
echo "If inputs is accessed as \${{ inputs.mode }}, it SHOULD work."
echo "Let's check Route event script carefully."
echo "              if [[ \"\${{ inputs.mode }}\" == release-* ]]; then"
echo "What if inputs.mode evaluates to an empty string because it's not present for some reason? But we KNOW it evaluates to something starting with 'release-' because prepare-release-tag ran, and its condition uses startsWith(inputs.mode, 'release-')."
echo "Wait! prepare-release-tag depends on 'inputs.mode' in its IF condition."
echo "If inputs.mode starts with 'release-', then in the Route event step, \${{ inputs.mode }} is also 'release-something'."
echo "Then '[[ \"release-something\" == release-* ]]' MUST be true."
echo "Then 'run_release=true' MUST be executed."
echo "Then 'echo \"run_release=\$run_release\" >> \"\$GITHUB_OUTPUT\"' MUST output 'run_release=true'."
echo "Then needs.route.outputs.run_release MUST be 'true'."
echo "IF all this is true, why did build-release-deb NOT run?"
echo "Maybe 'uraimo/run-on-arch-action@v2' is not working or has an issue? No, if it failed it would show as failed."
