echo "Wait, let's look at the blog post again:"
echo "              if [[ \"\${{ inputs.mode }}\" == release-* ]]; then"
echo "Is it possible that github.event_name is 'push' but 'github.ref' does NOT match 'refs/tags/*'?"
echo "If I look at the commit that was run in 29394511279, it is c751be306141933c8aad61a6b844cdb06f386f74"
echo "It is a commit on 'master' branch."
echo "If it is a workflow_dispatch, github.ref is 'refs/heads/master'."
echo "And inputs.mode was 'release-*' (because prepare-release-tag ran)."
echo "If prepare-release-tag ran, it outputs 'release_tag' (e.g. 'v1.0.1')."
echo "And 'publish-release' depends on it."
echo "Wait! The user said: 'I am expecting github releases with downloads when I run a tag release as per arran4.github.io/blog/post/2026/011-simplified-github-ci/'"
echo "Maybe the problem is that 'publish-release' only triggers if it's a push of a tag, AND ALSO for workflow dispatch..."
echo "Wait! If it triggers for workflow dispatch, the tag is CREATED by 'prepare-release-tag'."
echo "And then 'publish-release' creates a github release."
echo "BUT! Where does 'build-release-deb' run?"
echo "It runs ON THE CURRENT COMMIT (master branch), NOT ON THE TAG!"
echo "If it runs on the master branch, it uploads an artifact 'pocket-home-deb'."
echo "Then 'publish-release' downloads it."
echo "Wait! Could it be that 'build-release-deb' actually DID run, but I just didn't see it because it was dropped?"
