echo "Wait, when you look at ci.yml in Route event, the inputs.mode variable is checked like this:"
echo "              if [[ \"\${{ inputs.mode }}\" == release-* ]]; then"
echo "What if the user provided inputs.mode=release-minor?"
echo "If so, run_release evaluates to true."
echo "If run_release is true, build-release-deb should RUN."
echo "BUT build-release-deb did NOT run in 29394511279."
echo "This means run_release must be FALSE in 29394511279."
echo "Wait, if run_release is FALSE, why did prepare-release-tag RUN?"
echo "Because prepare-release-tag depends on startsWith(inputs.mode, 'release-'), NOT run_release!"
echo "Is it possible that github actions evaluated \${{ inputs.mode }} as EMPTY in the 'run' script but startsWith(inputs.mode, 'release-') correctly?"
echo "YES! In GitHub Actions, 'inputs' context is sometimes only available in 'if', and you MUST use 'github.event.inputs' in 'run' block??"
echo "Wait! Since Oct 2021, 'inputs' is available in 'run' block as well."
echo "But let's check GitHub Actions documentation for inputs."
echo "Wait! The user mentions:"
echo "\"I am expecting github releases with downloads when I run a tag release\""
echo "Wait! A tag release is when they PUSH a tag!"
echo "If they push a tag, github.event_name is 'push'. github.ref is 'refs/tags/...'."
echo "run_release evaluates to true."
echo "build-release-deb evaluates to true."
echo "publish-release has 'needs: [route, build-release-deb, prepare-release-tag]'."
echo "prepare-release-tag has 'if: \${{ github.event_name == 'workflow_dispatch' && startsWith(inputs.mode, 'release-') }}'."
echo "So prepare-release-tag SKIPS!"
echo "Since it SKIPS, publish-release is ALSO skipped, unless it has '!failure() && !cancelled()'."
echo "publish-release DOES HAVE '!failure() && !cancelled()'."
echo "Wait! Let me double check if '!failure() && !cancelled()' makes it run when a dependency is skipped."
echo "YES, according to GitHub Actions docs, if you specify ANY status check function in an if, the job runs regardless of the dependencies' statuses (unless explicitly checked like needs.foo.result == 'success')."
echo "BUT wait! If it runs, what happens to needs.prepare-release-tag.outputs.release_tag?"
echo "It's empty."
echo "In publish-release:"
echo "          TAG: \${{ github.event_name == 'workflow_dispatch' && needs.prepare-release-tag.outputs.release_tag || github.ref_name }}"
echo "Since github.event_name is 'push', it uses github.ref_name (e.g. v1.2.3). That's fine."
echo "Wait, so why doesn't it work?"
