echo "Ah, look at github.ref_name for tags. If you push refs/tags/v1.0.0, github.ref_name is 'v1.0.0'."
echo "But if you look at the user's issue: 'I am expecting github releases with downloads when I run a tag release as per arran4.github.io/blog/post/2026/011-simplified-github-ci/'"
echo "If I look at the blog post, it says:"
echo "'If you want a known-good baseline for manual dispatch semantics...'"
echo "'Important GoReleaser v2 note: avoid --tag in action args...'"
echo "Wait! The user mentions they expected 'github releases with downloads' when they run a tag release, but 'publish-release' creates a github release without downloads?"
echo "Wait, 'gh release create \"\$TAG\" new-deb/*.deb'"
echo "Wait! 'build-release-deb' uses 'out/pocket-home_*.deb'!"
echo "And 'publish-release' downloads it to 'new-deb'."
echo "Let's check 'publish-release':"
echo "      - name: Download Artifact"
echo "        uses: actions/download-artifact@v4"
echo "        with:"
echo "          name: pocket-home-deb"
echo "          path: new-deb"
echo "Wait. If 'build-release-deb' doesn't run, there is no artifact to download!"
echo "If there is no artifact, actions/download-artifact@v4 FAILS!"
echo "But wait. If build-release-deb did not run in 29394511279, then the artifact is definitely missing."
echo "Why did 'build-release-deb' NOT run in 29394511279?"
echo "Let's fix run_release logic!"
