echo "Wait..."
echo "Is it possible that build-release-deb DID NOT RUN because 'route' job has:"
echo "      run_release: \${{ steps.route.outputs.run_release }}"
echo "And in the script:"
echo "          echo \"run_release=\$run_release\" >> \"\$GITHUB_OUTPUT\""
echo "But the steps ID is 'route'."
echo "Wait! The step ID is 'route'. The job ID is 'route'."
echo "Are outputs defined correctly?"
echo "    outputs:"
echo "      run_release: \${{ steps.route.outputs.run_release }}"
echo "Yes."
echo "Let me check the run 29394511279 route job logs to see the outputs!"
