echo "Ah! Wait, if it's evaluated to true, why did build-release-deb NOT RUN in the run 29394511279?"
echo "Let's check the outputs of the Route event job for 29394511279."
echo "If I cannot view it, maybe inputs.mode was NOT 'release-*' for some reason!"
echo "If the user triggered the workflow dispatch from the UI, and left the inputs to their defaults, what is the default for 'mode'?"
echo "The default for 'mode' is 'lint-fix'!"
echo "If mode is 'lint-fix', then run_release is false!"
echo "If run_release is false, build-release-deb doesn't run!"
echo "But if mode was 'lint-fix', then prepare-release-tag should NOT have run either!"
echo "Because its condition is: if: \${{ github.event_name == 'workflow_dispatch' && startsWith(inputs.mode, 'release-') }}"
echo "But we saw that prepare-release-tag DID run in 29394511279!"
echo "So inputs.mode MUST HAVE BEEN 'release-*'."
